export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST"
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS"
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL"

export const GET_CART_HISTROY_REQUEST = "GET_CART_HISTROY_REQUEST"
export const GET_CART_HISTROY_SUCCESS = "GET_CART_HISTROY_SUCCESS"
export const GET_CART_HISTROY_FAIL = "GET_CART_HISTROY_FAIL"


export const DELETE_CART_REQUEST = " DELETE_CART_REQUEST"
export const DELETE_CART_SUCCESS = "DELETE_CART_SUCCESS"
export const DELETE_CART_FAIL = "DELETE_CART_FAIL"



export const DELETE_SINGLE_CART_ITEM_REQUEST = "DELETE_SINGLE_CART_ITEM_REQUEST"
export const DELETE_SINGLE_CART_ITEM_SUCCESS = "DELETE_SINGLE_CART_ITEM_SUCCESS"
export const DELETE_SINGLE_CART_ITEM_FAIL = "DELETE_SINGLE_CART_ITEM_FAIL"