export const PLACE_ORDER_REQUEST = "PLACE_ORDER_REQUEST"
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS"
export const PLACE_ORDER_FAIL = "PLACE_ORDER_FAIL"

export const ORDER_CANCEL_REQUEST = "ORDER_CANCEL_REQUEST"
export const ORDER_CANCEL_SUCCESS = "ORDER_CANCEL_SUCCESS"
export const ORDER_CANCEL_FAIL = "ORDER_CANCEL_FAIL"



export const USER_ORDER_HISTOPY_REQUEST = "USER_ORDER_HISTOPY_REQUEST"
export const USER_ORDER_HISTOPY_SUCCESS = "USER_ORDER_HISTOPY_SUCCESS"
export const USER_ORDER_HISTOPY_FAIL = "USER_ORDER_HISTOPY_FAIL"


export const INITIATE_PAYMENT_REQUEST = "INITIATE_PAYMENT_REQUEST"
export const INITIATE_PAYMENT_SUCCESS = "INITIATE_PAYMENT_SUCCESS"
export const INITIATE_PAYMENT_FAIL = "INITIATE_PAYMENT_FAIL"

export const PAYMENT_VERIFY_REQUEST = "PAYMENT_VERIFY_REQUEST"
export const PAYMENT_VERIFY_SUCCESS = "PAYMENT_VERIFY_SUCCESS"
export const PAYMENT_VERIFY_FAIL = "PAYMENT_VERIFY_FAIL"

export const PAYMENT_FAILED_REQUEST = "PAYMENT_FAILED_REQUEST"
export const PAYMENT_FAILED_SUCCESS = "PAYMENT_FAILED_SUCCESS"
export const PAYMENT_FAILED_FAIL = "PAYMENT_FAILED_FAIL"

export const BUY_NOW_REQUEST = "BUY_NOW_REQUEST"
export const BUY_NOW_SUCCESS = "BUY_NOW_SUCCESS"
export const BUY_NOW_FAIL = "BUY_NOW_FAIL"