




export const PRODUCT_GET_REQUEST = "PRODUCT_GET_REQUEST"
export const PRODUCT_GET_SUCCESS = "PRODUCT_GET_SUCCESS"
export const PRODUCT_GET_FAIL = "PRODUCT_GET_FAIL"

export const PRODUCT_GET_INFINITE_REQUEST = "PRODUCT_GET_INFINITE_REQUEST"
export const PRODUCT_GET_INFINITE_SUCCESS = "PRODUCT_GET_INFINITE_SUCCESS"
export const PRODUCT_GET_INFINITE_FAIL = "PRODUCT_GET_INFINITE_FAIL"

export const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST"
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS"
export const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL"

