export const EMPLOYEE_REGISTER_REQUEST = "EMPLOYEE_REGISTER_REQUEST"
export const EMPLOYEE_REGISTER_SUCCESS = "EMPLOYEE_REGISTER_SUCCESS"
export const EMPLOYEE_REGISTER_FAIL = "EMPLOYEE_REGISTER_FAIL"


export const EMPLOYEE_LOGIN_REQUEST = "EMPLOYEE_LOGIN_REQUEST"
export const EMPLOYEE_LOGIN_SUCCESS = "EMPLOYEE_LOGIN_SUCCESS"
export const EMPLOYEE_LOGIN_FAIL = "EMPLOYEE_LOGIN_FAIL"



export const EMPLOYEE_LOGOUT_SUCCESS = "EMPLOYEE_LOGOUT_SUCCESS"

//////////////////////////////////ADMIN/////////////////////////////////////////

export const EMPLOYEE_PRODUCT_ADD_REQUEST = "EMPLOYEE_PRODUCT_ADD_REQUEST"
export const EMPLOYEE_PRODUCT_ADD_SUCCESS = "EMPLOYEE_PRODUCT_ADD_SUCCESS"
export const EMPLOYEE_PRODUCT_ADD_FAIL = "EMPLOYEE_PRODUCT_ADD_FAIL"

export const ADMIN_GET_PRODUCT_REQUEST = "ADMIN_GET_PRODUCT_REQUEST"
export const ADMIN_GET_PRODUCT_SUCCESS = "ADMIN_GET_PRODUCT_SUCCESS"
export const ADMIN_GET_PRODUCT_FAIL = "ADMIN_GET_PRODUCT_FAIL"




export const ADMIN_PRODUCT_UPDATE_REQUEST = "ADMIN_PRODUCT_UPDATE_REQUEST"
export const ADMIN_PRODUCT_UPDATE_SUCCESS = "ADMIN_PRODUCT_UPDATE_SUCCESS"
export const ADMIN_PRODUCT_UPDATE_FAIL = "ADMIN_PRODUCT_UPDATE_FAIL"


export const EMPLOYEE_GET_SINGLE_PRODUCT_REQUEST = "EMPLOYEE_GET_SINGLE_PRODUCT_REQUEST"
export const EMPLOYEE_GET_SINGLE_PRODUCT_SUCCESS = "EMPLOYEE_GET_SINGLE_PRODUCT_SUCCESS"
export const EMPLOYEE_GET_SINGLE_PRODUCT_FAIL = "EMPLOYEE_GET_SINGLE_PRODUCT_FAIL"



export const ADMIN_PRODUCT_DELETE_REQUEST = "ADMIN_PRODUCT_DELETE_REQUEST"
export const ADMIN_PRODUCT_DELETE_SUCCESS = "ADMIN_PRODUCT_DELETE_SUCCESS"
export const ADMIN_PRODUCT_DELETE_FAIL = "ADMIN_PRODUCT_DELETE_FAIL"

/////////////////////////////////Login Adlin////////////////////////////////////////////////
export const ADMIN_LOGIN_REQUEST = "ADMIN_LOGIN_REQUEST"
export const ADMIN_LOGIN_SUCCESS = "ADMIN_LOGIN_SUCCESS"
export const ADMIN_LOGIN_FAIL = "ADMIN_LOGIN_FAIL"



export const ADMIN_LOGOUT_SUCCESS = "ADMIN_LOGOUT_SUCCESS"
///////////////////////////////////admin Stat/////////////////////////////////
export const GET_STAT_REQUEST = "GET_STAT_REQUEST"
export const GET_STAT_SUCCESS = "GET_STAT_SUCCESS"
export const GET_STAT_FAIL = "GET_STAT_FAIL"
