export const GET_ALL_ADMIN_USERS_REQUEST = "GET_ALL_ADMIN_USERS_REQUEST"
export const GET_ALL_ADMIN_USERS_SUCCESS = "GET_ALL_ADMIN_USERS_SUCCESS"
export const GET_ALL_ADMIN_USERS_FAIL = "GET_ALL_ADMIN_USERS_FAIL"

export const UPDATE_USER_STATUS_REQUEST = "UPDATE_USER_STATUS_REQUEST"
export const UPDATE_USER_STATUS_SUCCESS = "UPDATE_USER_STATUS_SUCCESS"
export const UPDATE_USER_STATUS_FAIL = "UPDATE_USER_STATUS_FAIL"